-- Add columns needed for frontend compatibility
ALTER TABLE products ADD COLUMN IF NOT EXISTS legacy_id integer UNIQUE;
ALTER TABLE products ADD COLUMN IF NOT EXISTS collection TEXT;

-- Enable real-time for products table
ALTER PUBLICATION supabase_realtime ADD TABLE products;

-- Seed all built-in products
INSERT INTO products (id, legacy_id, name, slug, description, price, compare_at_price, currency, category, collection, badge, features, images, in_stock)
VALUES
  ('00000000-0000-0000-0000-000000000001', 1, 'Cinematic Color LUTs Vol.1', 'cinematic-color-luts-vol1', '50 professional cinematic LUTs for Premiere Pro. Transform your footage with Hollywood-grade color grading in one click.', 2900, NULL, 'INR', 'Presets', 'presets', 'Best Seller', '["50 cinematic LUTs","Teal & orange palette","Warm summer tones","Moody noir looks","Commercial grade","Tutorial included"]', '["product-color-presets.svg"]', true),
  ('00000000-0000-0000-0000-000000000002', 2, 'VHS Glitch Effect Presets', 'vhs-glitch-effect-presets', '30 retro VHS and glitch effect presets for Premiere Pro. Add authentic tape distortion, scan lines, chroma shift, and static noise.', 1500, NULL, 'INR', 'Presets', 'presets', 'Popular', '["30 glitch presets","VHS distortion","Scan lines","Chroma shift","Static noise","Tutorial included"]', '["product-glow.svg"]', true),
  ('00000000-0000-0000-0000-000000000003', 3, 'Pastel Color Grading Bundle', 'pastel-color-grading-bundle', '40 soft pastel color grading presets for Premiere Pro. Create dreamy, aesthetic looks with muted tones.', 2100, NULL, 'INR', 'Presets', 'presets', NULL, '["40 pastel presets","Muted tones","Desaturated highlights","Aesthetic looks","Skin-safe colors","Video tutorial"]', '["product-color-mini.svg"]', true),
  ('00000000-0000-0000-0000-000000000004', 4, 'Duotone Color Presets', 'duotone-color-presets', '25 duotone color grading presets for Premiere Pro. Bold two-tone looks inspired by album covers.', 1600, NULL, 'INR', 'Presets', 'presets', 'Popular', '["25 duotone presets","Bold two-tone looks","Album cover style","Fashion editorial","Social media ready","Custom color swap"]', '["product-free-preset.svg"]', true),
  ('00000000-0000-0000-0000-000000000005', 5, 'Film Grain Overlay Pack', 'film-grain-overlay-pack', '15 authentic film grain overlay presets for Premiere Pro. 8mm, 16mm, and 35mm grain textures.', 1200, NULL, 'INR', 'Presets', 'presets', NULL, '["15 grain presets","8mm / 16mm / 35mm","Adjustable intensity","Vintage look","4K ready","Drag and drop"]', '["product-free-preset2.svg"]', true),
  ('00000000-0000-0000-0000-000000000006', 6, 'Smooth Slide Transitions Pack', 'smooth-slide-transitions-pack', '60 fluid slide transitions for Premiere Pro. Perfect for vlogs, travel videos, and social media content.', 1900, 3500, 'INR', 'Motion Graphics', 'motion-graphics', 'Best Seller', '["60 slide transitions","Drag-and-drop","Customizable direction","Speed controls","4K resolution","Video tutorial"]', '["product-ultimate-presets.svg"]', true),
  ('00000000-0000-0000-0000-000000000007', 7, 'Modern Broadcast Title Pack', 'modern-broadcast-title-pack', '30 professional broadcast-style title animations for Premiere Pro. News-style lower thirds and full-screen titles.', 2400, NULL, 'INR', 'Motion Graphics', 'motion-graphics', 'Popular', '["30 title animations","Broadcast quality","Lower thirds","Full-screen titles","Callout graphics","MOGR format"]', '["product-text-presets.svg"]', true),
  ('00000000-0000-0000-0000-000000000008', 8, 'Kinetic Typography Toolkit', 'kinetic-typography-toolkit', '80 animated kinetic typography templates for Premiere Pro. Dynamic text reveals and word-by-word animations.', 3200, NULL, 'INR', 'Motion Graphics', 'motion-graphics', 'Popular', '["80 typography templates","Word-by-word animation","Dynamic reveals","Music video ready","Social media optimized","MOGR format"]', '["product-text-animator.svg"]', true),
  ('00000000-0000-0000-0000-000000000009', 9, 'Morph Transition Pack', 'morph-transition-pack', '20 fluid morph transitions for Premiere Pro. Shape-shifting wipes, liquid distortions, and organic blends.', 2800, 3600, 'INR', 'Motion Graphics', 'motion-graphics', NULL, '["20 morph transitions","Shape-shifting wipes","Liquid distortions","Organic blends","4K ready","Drag and drop"]', '["product-paper-fold.svg"]', true),
  ('00000000-0000-0000-0000-000000000010', 10, '3D Lower Thirds Pack', '3d-lower-thirds-pack', '30 animated 3D lower thirds for Premiere Pro. Depth-split name tags and extruded titles.', 2400, NULL, 'INR', 'Motion Graphics', 'motion-graphics', 'Best Seller', '["30 lower thirds","3D depth effect","Extruded titles","Camera matched","Custom colors","MOGR format"]', '["product-number-counter.svg"]', true),
  ('00000000-0000-0000-0000-000000000011', 11, 'YouTube Master Project File', 'youtube-master-project-file', 'Complete YouTube video project file for Premiere Pro. Includes intro, outro, transitions, and more.', 4900, 7900, 'INR', 'Project Files', 'project-files', 'Best Seller', '["Full project file","Animated intro","Custom outro","CTA animations","Color grade presets","4K timeline ready"]', '["placeholder-13.svg"]', true),
  ('00000000-0000-0000-0000-000000000012', 12, 'Cinematic Travel Vlog Project', 'cinematic-travel-vlog', 'Complete Premiere Pro project file for a cinematic travel vlog. Includes sequences, transitions, and color grading.', 2499, 3499, 'INR', 'Project Files', 'project-files', 'Popular', '["Full project structure","Color graded sequences","Custom transitions","Motion graphics overlays","Sound design included","4K source footage"]', '["placeholder-1.svg"]', true),
  ('00000000-0000-0000-0000-000000000013', 13, 'Music Video Production Kit', 'music-video-production-kit', 'Professional music video project file with beat-synced editing, lyrical typography, and creative transitions.', 3499, 4499, 'INR', 'Project Files', 'project-files', NULL, '["Beat-synced timeline","Lyric typography template","Glitch transitions","Color LUTs included","Particle overlays","Tutorial walkthrough"]', '["placeholder-3.svg"]', true),
  ('00000000-0000-0000-0000-000000000014', 14, 'Wedding Highlights Master Project', 'wedding-highlights-master', 'Premium wedding highlight reel project file. Romantic transitions, elegant typography, and cinematic color grading.', 3999, 4999, 'INR', 'Project Files', 'project-files', 'Best Seller', '["Romantic transition pack","Elegant lower thirds","Cinematic LUTs","Highlight reel template","Photo slideshow module","Audio spectrum visuals"]', '["placeholder-5.svg"]', true),
  ('00000000-0000-0000-0000-000000000015', 15, 'Corporate Branding Project', 'corporate-branding-project', 'Complete corporate branding project file for Premiere Pro. Logo reveals, title sequences, and lower thirds.', 2999, NULL, 'INR', 'Project Files', 'project-files', 'Popular', '["Logo reveal animations","Title sequences","Lower thirds pack","Social media versions","Brand color presets","Export templates"]', '["placeholder-4.svg"]', true),
  ('00000000-0000-0000-0000-000000000016', 16, 'Cinematic Overlays Bundle', 'cinematic-overlays-bundle', '20 free cinematic overlay effects for Premiere Pro. Dust particles, light leaks, film grain, and bokeh overlays.', 0, NULL, 'INR', 'Free Assets', 'free-assets', 'Free', '["20 free overlays","Dust particles","Light leaks","Film grain","Bokeh effects","4K resolution"]', '["placeholder-9.svg"]', true),
  ('00000000-0000-0000-0000-000000000017', 17, 'Speed Ramp Transitions', 'speed-ramp-transitions', '10 free speed ramp transitions for Premiere Pro. Add cinematic speed changes to your edits.', 0, NULL, 'INR', 'Free Assets', 'free-assets', 'Free', '["10 speed ramp presets","Cinematic time remapping","Easy to customize","Free download","Works with any footage","Tutorial included"]', '["placeholder-10.svg"]', true),
  ('00000000-0000-0000-0000-000000000018', 18, 'Typewriter Animation Template', 'typewriter-animation-template', 'Free typewriter text animation template for Premiere Pro. A classic typing effect with customizable text.', 0, NULL, 'INR', 'Free Assets', 'free-assets', 'Free', '["Typewriter effect","Customizable text","Adjustable speed","Sound effects included","Free download","HD resolution"]', '["product-typewriter.svg"]', true),
  ('00000000-0000-0000-0000-000000000019', 19, 'Social Media Story Pack', 'social-media-story-pack-free', 'Free social media video kit for Premiere Pro. 10 vertical story templates and 5 reel intros.', 0, NULL, 'INR', 'Free Assets', 'free-assets', 'Free', '["10 story templates","5 reel intros","3 transition sets","9:16 vertical format","Instagram optimized","TikTok ready"]', '["placeholder-6.svg"]', true),
  ('00000000-0000-0000-0000-000000000020', 20, 'Audio Visualizer Pack', 'audio-visualizer-pack-free', 'Free audio visualization presets for Premiere Pro. 8 spectrum analyzers and waveform animations.', 0, NULL, 'INR', 'Free Assets', 'free-assets', 'Free', '["8 visualizers","Spectrum analyzer","Waveform animation","Beat-reactive","Music content","Podcast ready"]', '["placeholder-4.svg"]', true),
  ('00000000-0000-0000-0000-000000000021', 21, 'Cinematic Sound Effects Vol.1', 'cinematic-sound-effects-vol1', '100 professional cinematic sound effects for video editors. Whooshes, impacts, risers, and ambient drones.', 2200, NULL, 'INR', 'Sound Effects', 'sound-effects', 'Best Seller', '["100 sound effects","Whooshes & impacts","Risers & hits","Ambient drones","Transition sounds","Royalty-free"]', '["placeholder-11.svg"]', true),
  ('00000000-0000-0000-0000-000000000022', 22, 'Vocal Chop & Stutter Pack', 'vocal-chop-stutter-pack', '50 vocal chop and stutter sound effects for Premiere Pro. Perfect for modern video edits and transitions.', 1800, NULL, 'INR', 'Sound Effects', 'sound-effects', NULL, '["50 vocal effects","Stutter sounds","Vocal chops","Rhythmic accents","Music content ready","Instant download"]', '["placeholder-12.svg"]', true),
  ('00000000-0000-0000-0000-000000000023', 23, 'Ambient Background Drones', 'ambient-background-drones', '30 ambient drone soundscapes for video editing. Cinematic backgrounds and tension builders.', 1400, NULL, 'INR', 'Sound Effects', 'sound-effects', NULL, '["30 ambient drones","Cinematic backgrounds","Tension builders","Atmospheric pads","Royalty-free","Loopable"]', '["placeholder-14.svg"]', true),
  ('00000000-0000-0000-0000-000000000024', 24, 'Transition Whoosh Bundle', 'transition-whoosh-bundle', '75 whoosh sound effects for smooth video transitions. Sweep whooshes, sub drops, and airy passes.', 1600, 2500, 'INR', 'Sound Effects', 'sound-effects', 'Popular', '["75 whoosh sounds","Sweep whooshes","Sub drops","Airy passes","Mechanical swooshes","Ready to sync"]', '["placeholder-15.svg"]', true),
  ('00000000-0000-0000-0000-000000000025', 25, 'UI Notification Sound Kit', 'ui-notification-sound-kit', '40 UI notification sounds for video content. Pop sounds, dings, alerts, chimes, and tech UI feedback.', 900, NULL, 'INR', 'Sound Effects', 'sound-effects', NULL, '["40 UI sounds","Pop sounds","Dings & alerts","Chimes","Tech UI feedback","Social media ready"]', '["placeholder-8.svg"]', true),
  ('00000000-0000-0000-0000-000000000026', 26, 'Neon Title Presets', 'neon-title-presets', '25 neon glow title presets for Premiere Pro. Cyberpunk-style animated text with customizable colors.', 1900, 2600, 'INR', 'Presets', 'presets', 'Popular', '["25 neon titles","Custom colors","Glow intensity control","Flicker effects","Cyberpunk style","MOGR format"]', '["placeholder-11.svg"]', true),
  ('00000000-0000-0000-0000-000000000027', 27, 'Vintage Film LUTs Collection', 'vintage-film-luts-collection', '30 vintage film LUTs for Premiere Pro. Kodachrome, Fujifilm, and expired film stock emulations.', 2500, NULL, 'INR', 'Presets', 'presets', 'Best Seller', '["30 vintage LUTs","Kodachrome emulation","Fujifilm emulation","Expired film stock","Grain matching","Tutorial included"]', '["placeholder-9.svg"]', true),
  ('00000000-0000-0000-0000-000000000028', 28, 'HDR Transition Effects Pack', 'hdr-transition-effects-pack', '50 HDR transition effects for Premiere Pro. Light leaks, lens flares, chromatic aberration, and bloom transitions.', 1800, 2500, 'INR', 'Presets', 'presets', 'Best Seller', '["50 HDR transitions","Light leaks","Lens flares","Chromatic aberration","Bloom effects","4K ready"]', '["product-glow.svg"]', true)
ON CONFLICT (legacy_id) DO NOTHING;

-- Update legacy products that already exist (in case seed runs after table has data)
UPDATE products SET
  collection = CASE
    WHEN category = 'Presets' THEN 'presets'
    WHEN category = 'Motion Graphics' THEN 'motion-graphics'
    WHEN category = 'Project Files' THEN 'project-files'
    WHEN category = 'Free Assets' THEN 'free-assets'
    WHEN category = 'Sound Effects' THEN 'sound-effects'
    ELSE 'uncategorized'
  END
WHERE collection IS NULL AND legacy_id IS NOT NULL;
